name: gma_all_mediations
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.6+1
  flutter:
    sdk: flutter
  gma_mediation_applovin: ^2.5.2
  gma_mediation_chartboost: 1.4.0
  gma_mediation_dtexchange: ^1.3.3
  gma_mediation_inmobi: ^2.0.1
  gma_mediation_ironsource: ^2.3.0
  gma_mediation_liftoffmonetize: ^1.4.3
  gma_mediation_meta: ^1.5.1
  gma_mediation_mintegral: ^2.0.3
  gma_mediation_unity: ^1.6.5
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fluxpert.gma_all_mediations
        pluginClass: GmaAllMediationsPlugin
      ios:
        pluginClass: GmaAllMediationsPlugin
